<?php

namespace Modules\Accounts\Database\Seeders;

use Illuminate\Database\Seeder;

class AccReportFormateTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('acc_report_formate')->truncate();
        
        \DB::table('acc_report_formate')->insert(array (
            0 => 
            array (
                'id' => 1,
                'report_id' => 1,
                'srl' => 1,
                'r_sign' => '',
                'r_space' => '',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 102,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Sales',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'report_id' => 1,
                'srl' => 2,
                'r_sign' => '-',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 104,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Sales Return',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'report_id' => 1,
                'srl' => 3,
                'r_sign' => '=',
                'r_space' => '',
                'p_srl_row_val_1' => 1,
                'p_colum_amount_1' => 'A',
                'p_sign' => '+',
                'p_srl_row_val_2' => 2,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Total Sales',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'report_id' => 1,
                'srl' => 4,
                'r_sign' => '-',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 103,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Sales Discount',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'report_id' => 1,
                'srl' => 5,
                'r_sign' => '=',
                'r_space' => '',
                'p_srl_row_val_1' => 3,
                'p_colum_amount_1' => 'A',
                'p_sign' => '-',
                'p_srl_row_val_2' => 4,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Net Sales',
                'value_colum' => 'B',
                'is_active' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'report_id' => 1,
                'srl' => 6,
                'r_sign' => '-',
                'r_space' => '&nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'COGS',
                'value_colum' => '',
                'is_active' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'report_id' => 1,
                'srl' => 7,
                'r_sign' => '',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 57,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Inventory OB',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'report_id' => 1,
                'srl' => 8,
                'r_sign' => '+',
                'r_space' => '&nbsp; &nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 85,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Purchases',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'report_id' => 1,
                'srl' => 9,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => 7,
                'p_colum_amount_1' => 'A',
                'p_sign' => '+',
                'p_srl_row_val_2' => 8,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Total Purchases',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'report_id' => 1,
                'srl' => 10,
                'r_sign' => '-',
                'r_space' => '&nbsp; &nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 84,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Purchases Return',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'report_id' => 1,
                'srl' => 11,
                'r_sign' => '-',
                'r_space' => '&nbsp; &nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => 82,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Purchases Discount',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'report_id' => 1,
                'srl' => 12,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp; &nbsp;',
                'p_srl_row_val_1' => 10,
                'p_colum_amount_1' => 'A',
                'p_sign' => '+',
                'p_srl_row_val_2' => 11,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
            'account_name' => 'Total Purchases (Contra) ',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'report_id' => 1,
                'srl' => 13,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => 9,
                'p_colum_amount_1' => 'A',
                'p_sign' => '-',
                'p_srl_row_val_2' => 12,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Gross Purchases',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'report_id' => 1,
                'srl' => 14,
                'r_sign' => '-',
                'r_space' => '&nbsp; &nbsp; &nbsp;&nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => 25,
                'account_name' => 'Total Purchases Cost',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'report_id' => 1,
                'srl' => 15,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => 13,
                'p_colum_amount_1' => 'A',
                'p_sign' => '+',
                'p_srl_row_val_2' => 12,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Net Purchases',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'report_id' => 1,
                'srl' => 16,
                'r_sign' => '',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Inventory CB',
                'value_colum' => 'A',
                'is_active' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'report_id' => 1,
                'srl' => 17,
                'r_sign' => '=',
                'r_space' => '&nbsp;',
                'p_srl_row_val_1' => 15,
                'p_colum_amount_1' => 'A',
                'p_sign' => '-',
                'p_srl_row_val_2' => 16,
                'p_colum_amount_2' => 'A',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Total COGS',
                'value_colum' => 'B',
                'is_active' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'report_id' => 1,
                'srl' => 18,
                'r_sign' => '=',
                'r_space' => '',
                'p_srl_row_val_1' => 5,
                'p_colum_amount_1' => 'B',
                'p_sign' => '-',
                'p_srl_row_val_2' => 17,
                'p_colum_amount_2' => 'B',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Gross Profit/Loss',
                'value_colum' => 'C',
                'is_active' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'report_id' => 1,
                'srl' => 19,
                'r_sign' => '-',
                'r_space' => '',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Operrative Expenses',
                'value_colum' => '',
                'is_active' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'report_id' => 1,
                'srl' => 20,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => 9,
                'account_name' => 'Total Operrative Expenses',
                'value_colum' => 'B',
                'is_active' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'report_id' => 1,
                'srl' => 21,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => 18,
                'p_colum_amount_1' => 'C',
                'p_sign' => '-',
                'p_srl_row_val_2' => 20,
                'p_colum_amount_2' => 'B',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Operative Income',
                'value_colum' => 'C',
                'is_active' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'report_id' => 1,
                'srl' => 22,
                'r_sign' => '+',
                'r_space' => '',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Others Income',
                'value_colum' => '',
                'is_active' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'report_id' => 1,
                'srl' => 23,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => 12,
                'account_name' => 'Total Others Income',
                'value_colum' => 'B',
                'is_active' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'report_id' => 1,
                'srl' => 24,
                'r_sign' => '+',
                'r_space' => '',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Non Operating Expenses',
                'value_colum' => '',
                'is_active' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'report_id' => 1,
                'srl' => 25,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => 10,
                'account_name' => 'Total Non Operating Expenses',
                'value_colum' => 'B',
                'is_active' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'report_id' => 1,
                'srl' => 26,
                'r_sign' => '=',
                'r_space' => '',
                'p_srl_row_val_1' => 23,
                'p_colum_amount_1' => 'B',
                'p_sign' => '-',
                'p_srl_row_val_2' => 25,
                'p_colum_amount_2' => 'B',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Net Operating Income /Expenses ',
                'value_colum' => 'C',
                'is_active' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'report_id' => 1,
                'srl' => 27,
                'r_sign' => '=',
                'r_space' => '',
                'p_srl_row_val_1' => 21,
                'p_colum_amount_1' => 'C',
                'p_sign' => '+',
                'p_srl_row_val_2' => 26,
                'p_colum_amount_2' => 'C',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Net Profit/Loss Before Txa ',
                'value_colum' => 'C',
                'is_active' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'report_id' => 1,
                'srl' => 28,
                'r_sign' => '+',
                'r_space' => '&nbsp; ',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Tax',
                'value_colum' => '',
                'is_active' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'report_id' => 1,
                'srl' => 29,
                'r_sign' => '=',
                'r_space' => '&nbsp; &nbsp;&nbsp; &nbsp;',
                'p_srl_row_val_1' => NULL,
                'p_colum_amount_1' => NULL,
                'p_sign' => NULL,
                'p_srl_row_val_2' => NULL,
                'p_colum_amount_2' => NULL,
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => 133,
                'account_name' => 'Total Income Tax',
                'value_colum' => 'C',
                'is_active' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'report_id' => 1,
                'srl' => 30,
                'r_sign' => '=',
                'r_space' => '',
                'p_srl_row_val_1' => 27,
                'p_colum_amount_1' => 'C',
                'p_sign' => '-',
                'p_srl_row_val_2' => 29,
                'p_colum_amount_2' => 'C',
                'coa_acc_id' => NULL,
                'sub_coa_acc_id' => NULL,
                'account_name' => 'Net Profit/Loss After Tax ',
                'value_colum' => 'C',
                'is_active' => 1,
            ),
        ));

        
    }
}