<?php

namespace Modules\Accounts\Database\Seeders;

use Illuminate\Database\Seeder;

class AccVoucherDetailsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('acc_voucher_details')->truncate();
        
        \DB::table('acc_voucher_details')->insert(array (
            0 => 
            array (
                'id' => 55,
                'voucher_master_id' => 23,
                'acc_coa_id' => 53,
                'Dr_Amount' => '500.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => '',
                'chequeno' => '',
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            1 => 
            array (
                'id' => 56,
                'voucher_master_id' => 23,
                'acc_coa_id' => 102,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '500.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => '',
                'chequeno' => '',
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            2 => 
            array (
                'id' => 218,
                'voucher_master_id' => 91,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            3 => 
            array (
                'id' => 219,
                'voucher_master_id' => 91,
                'acc_coa_id' => 125,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            4 => 
            array (
                'id' => 220,
                'voucher_master_id' => 92,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            5 => 
            array (
                'id' => 221,
                'voucher_master_id' => 92,
                'acc_coa_id' => 125,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            6 => 
            array (
                'id' => 222,
                'voucher_master_id' => 93,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            7 => 
            array (
                'id' => 223,
                'voucher_master_id' => 93,
                'acc_coa_id' => 125,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            8 => 
            array (
                'id' => 224,
                'voucher_master_id' => 94,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            9 => 
            array (
                'id' => 225,
                'voucher_master_id' => 94,
                'acc_coa_id' => 125,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            10 => 
            array (
                'id' => 226,
                'voucher_master_id' => 94,
                'acc_coa_id' => 124,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            11 => 
            array (
                'id' => 227,
                'voucher_master_id' => 94,
                'acc_coa_id' => 126,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            12 => 
            array (
                'id' => 228,
                'voucher_master_id' => 94,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '130.000',
                'subtype_id' => 4,
                'subcode_id' => 3,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            13 => 
            array (
                'id' => 229,
                'voucher_master_id' => 95,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 3,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            14 => 
            array (
                'id' => 230,
                'voucher_master_id' => 95,
                'acc_coa_id' => 53,
                'Dr_Amount' => '1530.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            15 => 
            array (
                'id' => 231,
                'voucher_master_id' => 96,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            16 => 
            array (
                'id' => 232,
                'voucher_master_id' => 96,
                'acc_coa_id' => 125,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            17 => 
            array (
                'id' => 233,
                'voucher_master_id' => 96,
                'acc_coa_id' => 124,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            18 => 
            array (
                'id' => 234,
                'voucher_master_id' => 96,
                'acc_coa_id' => 126,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            19 => 
            array (
                'id' => 235,
                'voucher_master_id' => 96,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '130.000',
                'subtype_id' => 4,
                'subcode_id' => 3,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            20 => 
            array (
                'id' => 236,
                'voucher_master_id' => 97,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 3,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            21 => 
            array (
                'id' => 237,
                'voucher_master_id' => 97,
                'acc_coa_id' => 53,
                'Dr_Amount' => '1530.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            22 => 
            array (
                'id' => 246,
                'voucher_master_id' => 102,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            23 => 
            array (
                'id' => 247,
                'voucher_master_id' => 102,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 3,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            24 => 
            array (
                'id' => 248,
                'voucher_master_id' => 103,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            25 => 
            array (
                'id' => 249,
                'voucher_master_id' => 103,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            26 => 
            array (
                'id' => 250,
                'voucher_master_id' => 104,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            27 => 
            array (
                'id' => 251,
                'voucher_master_id' => 104,
                'acc_coa_id' => 4,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            28 => 
            array (
                'id' => 252,
                'voucher_master_id' => 104,
                'acc_coa_id' => 53,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            29 => 
            array (
                'id' => 253,
                'voucher_master_id' => 105,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            30 => 
            array (
                'id' => 254,
                'voucher_master_id' => 105,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            31 => 
            array (
                'id' => 255,
                'voucher_master_id' => 106,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            32 => 
            array (
                'id' => 256,
                'voucher_master_id' => 106,
                'acc_coa_id' => 4,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            33 => 
            array (
                'id' => 257,
                'voucher_master_id' => 106,
                'acc_coa_id' => 53,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            34 => 
            array (
                'id' => 258,
                'voucher_master_id' => 107,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            35 => 
            array (
                'id' => 259,
                'voucher_master_id' => 107,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            36 => 
            array (
                'id' => 260,
                'voucher_master_id' => 108,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            37 => 
            array (
                'id' => 261,
                'voucher_master_id' => 108,
                'acc_coa_id' => 4,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            38 => 
            array (
                'id' => 262,
                'voucher_master_id' => 108,
                'acc_coa_id' => 53,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            39 => 
            array (
                'id' => 263,
                'voucher_master_id' => 109,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            40 => 
            array (
                'id' => 264,
                'voucher_master_id' => 109,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            41 => 
            array (
                'id' => 265,
                'voucher_master_id' => 110,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            42 => 
            array (
                'id' => 266,
                'voucher_master_id' => 110,
                'acc_coa_id' => 53,
                'Dr_Amount' => '1530.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            43 => 
            array (
                'id' => 267,
                'voucher_master_id' => 110,
                'acc_coa_id' => 4,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            44 => 
            array (
                'id' => 269,
                'voucher_master_id' => 110,
                'acc_coa_id' => 53,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            45 => 
            array (
                'id' => 270,
                'voucher_master_id' => 111,
                'acc_coa_id' => 85,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            46 => 
            array (
                'id' => 271,
                'voucher_master_id' => 111,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '10.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            47 => 
            array (
                'id' => 272,
                'voucher_master_id' => 112,
                'acc_coa_id' => 110,
                'Dr_Amount' => '10.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            48 => 
            array (
                'id' => 273,
                'voucher_master_id' => 113,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            49 => 
            array (
                'id' => 274,
                'voucher_master_id' => 113,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            50 => 
            array (
                'id' => 275,
                'voucher_master_id' => 114,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            51 => 
            array (
                'id' => 276,
                'voucher_master_id' => 114,
                'acc_coa_id' => 4,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            52 => 
            array (
                'id' => 277,
                'voucher_master_id' => 114,
                'acc_coa_id' => 53,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            53 => 
            array (
                'id' => 278,
                'voucher_master_id' => 115,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            54 => 
            array (
                'id' => 279,
                'voucher_master_id' => 115,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            55 => 
            array (
                'id' => 280,
                'voucher_master_id' => 116,
                'acc_coa_id' => 110,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            56 => 
            array (
                'id' => 281,
                'voucher_master_id' => 116,
                'acc_coa_id' => 4,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            57 => 
            array (
                'id' => 282,
                'voucher_master_id' => 116,
                'acc_coa_id' => 53,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            58 => 
            array (
                'id' => 283,
                'voucher_master_id' => 117,
                'acc_coa_id' => 85,
                'Dr_Amount' => '150.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            59 => 
            array (
                'id' => 284,
                'voucher_master_id' => 117,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '150.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            60 => 
            array (
                'id' => 285,
                'voucher_master_id' => 118,
                'acc_coa_id' => 110,
                'Dr_Amount' => '150.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            61 => 
            array (
                'id' => 286,
                'voucher_master_id' => 118,
                'acc_coa_id' => 4,
                'Dr_Amount' => '150.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            62 => 
            array (
                'id' => 287,
                'voucher_master_id' => 118,
                'acc_coa_id' => 53,
                'Dr_Amount' => '150.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            63 => 
            array (
                'id' => 288,
                'voucher_master_id' => 119,
                'acc_coa_id' => 85,
                'Dr_Amount' => '100.000',
                'Cr_Amount' => '0.000',
                'subtype_id' => NULL,
                'subcode_id' => NULL,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
            64 => 
            array (
                'id' => 289,
                'voucher_master_id' => 119,
                'acc_coa_id' => 110,
                'Dr_Amount' => '0.000',
                'Cr_Amount' => '100.000',
                'subtype_id' => 4,
                'subcode_id' => 7,
                'LaserComments' => NULL,
                'chequeno' => NULL,
                'chequeDate' => NULL,
                'ishonour' => NULL,
            ),
        ));

        
    }
}