<?php

namespace Modules\Accounts\Database\Seeders;

use Illuminate\Database\Seeder;

class AccVoucherMasterTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('acc_voucher_master')->truncate();
        
        \DB::table('acc_voucher_master')->insert(array (
            0 => 
            array (
                'id' => 23,
                'VoucherNumber' => 'CV_2412_000001',
                'VoucherNumberMainBreanch' => 'CV_2412_000001',
                'VoucherDate' => '2024-12-23',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 2,
                'Voucher_event_code' => 'ACC',
                'TranAmount' => '500.00',
                'Remarks' => 'CS1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-23 19:14:00',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 1,
                'Approvedby' => '1',
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => NULL,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            1 => 
            array (
                'id' => 91,
                'VoucherNumber' => 'JV_2412_000001',
                'VoucherNumberMainBreanch' => 'JV_2412_000001',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:48:52',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            2 => 
            array (
                'id' => 92,
                'VoucherNumber' => 'JV_2412_000002',
                'VoucherNumberMainBreanch' => 'JV_2412_000002',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:49:13',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            3 => 
            array (
                'id' => 93,
                'VoucherNumber' => 'JV_2412_000003',
                'VoucherNumberMainBreanch' => 'JV_2412_000003',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:49:14',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            4 => 
            array (
                'id' => 94,
                'VoucherNumber' => 'JV_2412_000004',
                'VoucherNumberMainBreanch' => 'JV_2412_000004',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:54:14',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            5 => 
            array (
                'id' => 95,
                'VoucherNumber' => 'DV_2412_000001',
                'VoucherNumberMainBreanch' => 'DV_2412_000001',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:54:14',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            6 => 
            array (
                'id' => 96,
                'VoucherNumber' => 'JV_2412_000005',
                'VoucherNumberMainBreanch' => 'JV_2412_000005',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:55:41',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            7 => 
            array (
                'id' => 97,
                'VoucherNumber' => 'DV_2412_000002',
                'VoucherNumberMainBreanch' => 'DV_2412_000002',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '130.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 15:55:41',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            8 => 
            array (
                'id' => 102,
                'VoucherNumber' => 'JV_2412_000006',
                'VoucherNumberMainBreanch' => 'JV_2412_000006',
                'VoucherDate' => '2024-12-26',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'DPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'DPMP POS Purchases Number : 2',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-26 16:07:40',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 2,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            9 => 
            array (
                'id' => 103,
                'VoucherNumber' => 'JV_2412_000007',
                'VoucherNumberMainBreanch' => 'JV_2412_000007',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP Manage Purchases Number : 40',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:43:15',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 40,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            10 => 
            array (
                'id' => 104,
                'VoucherNumber' => 'DV_2412_000003',
                'VoucherNumberMainBreanch' => 'DV_2412_000003',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 40',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:43:15',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 40,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            11 => 
            array (
                'id' => 105,
                'VoucherNumber' => 'JV_2412_000008',
                'VoucherNumberMainBreanch' => 'JV_2412_000008',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP Manage Purchases Number : 41',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:44:23',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 41,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            12 => 
            array (
                'id' => 106,
                'VoucherNumber' => 'DV_2412_000004',
                'VoucherNumberMainBreanch' => 'DV_2412_000004',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 41',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:44:23',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 41,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            13 => 
            array (
                'id' => 107,
                'VoucherNumber' => 'JV_2412_000009',
                'VoucherNumberMainBreanch' => 'JV_2412_000009',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP Manage Purchases Number : 42',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:44:45',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 42,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            14 => 
            array (
                'id' => 108,
                'VoucherNumber' => 'DV_2412_000005',
                'VoucherNumberMainBreanch' => 'DV_2412_000005',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 42',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:44:45',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 42,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            15 => 
            array (
                'id' => 109,
                'VoucherNumber' => 'JV_2412_000010',
                'VoucherNumberMainBreanch' => 'JV_2412_000010',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:48:00',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            16 => 
            array (
                'id' => 110,
                'VoucherNumber' => 'DV_2412_000006',
                'VoucherNumberMainBreanch' => 'DV_2412_000006',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:48:00',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            17 => 
            array (
                'id' => 111,
                'VoucherNumber' => 'JV_2412_000011',
                'VoucherNumberMainBreanch' => 'JV_2412_000011',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '10.00',
                'Remarks' => 'SPMP Manage Purchases Number : 2',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:54:48',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 2,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            18 => 
            array (
                'id' => 112,
                'VoucherNumber' => 'DV_2412_000007',
                'VoucherNumberMainBreanch' => 'DV_2412_000007',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '10.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 2',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 15:54:48',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 2,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            19 => 
            array (
                'id' => 113,
                'VoucherNumber' => 'JV_2412_000012',
                'VoucherNumberMainBreanch' => 'JV_2412_000012',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP Manage Purchases Number : 4',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 16:03:39',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 4,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            20 => 
            array (
                'id' => 114,
                'VoucherNumber' => 'DV_2412_000008',
                'VoucherNumberMainBreanch' => 'DV_2412_000008',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 4',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 16:03:39',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 4,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            21 => 
            array (
                'id' => 115,
                'VoucherNumber' => 'JV_2412_000013',
                'VoucherNumberMainBreanch' => 'JV_2412_000013',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP Manage Purchases Number : 4',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 16:23:52',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 4,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            22 => 
            array (
                'id' => 116,
                'VoucherNumber' => 'DV_2412_000009',
                'VoucherNumberMainBreanch' => 'DV_2412_000009',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 4',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 16:23:52',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 4,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            23 => 
            array (
                'id' => 117,
                'VoucherNumber' => 'JV_2412_000014',
                'VoucherNumberMainBreanch' => 'JV_2412_000014',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '150.00',
                'Remarks' => 'SPMP Manage Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 18:22:43',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            24 => 
            array (
                'id' => 118,
                'VoucherNumber' => 'DV_2412_000010',
                'VoucherNumberMainBreanch' => 'DV_2412_000010',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 1,
                'Voucher_event_code' => 'SPMP',
                'TranAmount' => '150.00',
                'Remarks' => 'SPMP  Manage Payment Purchases Number : 1',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 18:22:43',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 1,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
            25 => 
            array (
                'id' => 119,
                'VoucherNumber' => 'JV_2412_000015',
                'VoucherNumberMainBreanch' => 'JV_2412_000015',
                'VoucherDate' => '2024-12-28',
                'Companyid' => 0,
                'BranchId' => 1,
                'FinancialYearId' => 2,
                'VoucharTypeId' => 3,
                'Voucher_event_code' => 'DPMP',
                'TranAmount' => '100.00',
                'Remarks' => 'DPMP POS Purchases Number : 7',
                'Createdby' => '39',
                'CreatedDate' => '2024-12-28 19:06:20',
                'UpdatedBy' => NULL,
                'UpdatedDate' => '1970-01-01 00:00:00',
                'IsApprove' => 0,
                'Approvedby' => NULL,
                'Approvedate' => '1970-01-01 00:00:00',
                'PurchaseID' => 7,
                'BillID' => NULL,
                'ServiceID' => NULL,
                'IsYearClosed' => 0,
                'preturn_id' => NULL,
                'oreturn_id' => NULL,
            ),
        ));

        
    }
}